name = "Interfaces"
uuid = "85a1e053-f937-4924-92a5-1367d23b7b87"
authors = ["Rafael Schouten <rafaelschouten@gmail.com>"]
version = "0.3.2"

[compat]
Aqua = "0.8"
Documenter = "1"
Test = "1"
julia = "1.6"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Documenter", "Test"]
